import { Schema } from "mongoose";

export const resourceIds = [
  "woodT1", "woodT2", "woodT3", "woodT4", "woodT5",
  "fiberT1", "fiberT2", "fiberT3", "fiberT4", "fiberT5",
  "oreT1", "oreT2", "oreT3", "oreT4", "oreT5",
  "coal",
  "ingotT1", "ingotT2", "ingotT3", "ingotT4", "ingotT5",
  "plankT1", "plankT2", "plankT3", "plankT4", "plankT5",
  "textileT1", "textileT2", "textileT3", "textileT4", "textileT5",
  "sapT1", "sapT2", "sapT3", "sapT4", "sapT5",
  "stickT1", "stickT2", "stickT3", "stickT4", "stickT5",
  "chunkT1", "chunkT2", "chunkT3", "chunkT4", "chunkT5",
  "speed_mining_charm", "exp_mining_charm", "luck_mining_charm", "yieldMin_mining_charm", "yieldMax_mining_charm",
  "speed_woodcutting_charm", "exp_woodcutting_charm", "luck_woodcutting_charm", "yieldMin_woodcutting_charm", "yieldMax_woodcutting_charm",
  "speed_harvesting_charm", "exp_harvesting_charm", "luck_harvesting_charm", "yieldMin_harvesting_charm", "yieldMax_harvesting_charm",
  "con_charm", "int_charm", "str_charm", "foc_charm", "dex_charm",
] as const

export type ResourceId = typeof resourceIds[number];
export const isResourceId = (resource: string): resource is ResourceId => resourceIds.includes(resource as ResourceId)
export type Resources = Record<ResourceId, number>;

  
export const resourcesSchema = new Schema<Resources>({
  woodT1: { type: Number, default: 0 },
  woodT2: { type: Number, default: 0 },
  woodT3: { type: Number, default: 0 },
  woodT4: { type: Number, default: 0 },
  woodT5: { type: Number, default: 0 },
  fiberT1: { type: Number, default: 0 },
  fiberT2: { type: Number, default: 0 },
  fiberT3: { type: Number, default: 0 },
  fiberT4: { type: Number, default: 0 },
  fiberT5: { type: Number, default: 0 },
  oreT1: { type: Number, default: 0 },
  oreT2: { type: Number, default: 0 },
  oreT3: { type: Number, default: 0 },
  oreT4: { type: Number, default: 0 },
  oreT5: { type: Number, default: 0 },
  coal: { type: Number, default: 0 },
  ingotT1: { type: Number, default: 0 },
  ingotT2: { type: Number, default: 0 },
  ingotT3: { type: Number, default: 0 },
  ingotT4: { type: Number, default: 0 },
  ingotT5: { type: Number, default: 0 },
  plankT1: { type: Number, default: 0 },
  plankT2: { type: Number, default: 0 },
  plankT3: { type: Number, default: 0 },
  plankT4: { type: Number, default: 0 },
  plankT5: { type: Number, default: 0 },
  textileT1: { type: Number, default: 0 },
  textileT2: { type: Number, default: 0 },
  textileT3: { type: Number, default: 0 },
  textileT4: { type: Number, default: 0 },
  textileT5: { type: Number, default: 0 },
  sapT1: { type: Number, default: 0 },
  sapT2: { type: Number, default: 0 },
  sapT3: { type: Number, default: 0 },
  sapT4: { type: Number, default: 0 },
  sapT5: { type: Number, default: 0 },
  stickT1: { type: Number, default: 0 },
  stickT2: { type: Number, default: 0 },
  stickT3: { type: Number, default: 0 },
  stickT4: { type: Number, default: 0 },
  stickT5: { type: Number, default: 0 },
  chunkT1: { type: Number, default: 0 },
  chunkT2: { type: Number, default: 0 },
  chunkT3: { type: Number, default: 0 },
  chunkT4: { type: Number, default: 0 },
  chunkT5: { type: Number, default: 0 },
}, {_id: false});